export const LOCAL_STORAGE_USER_ID = "planning_poker_id";
export const LOCAL_STORAGE_USER_NAME = "planning_poker_username";

export const SCALE_FIBONACCI = "fibonacci";
export const SCALE_T_SHIRT = "t_shirt";
export const SCALE_GAMER = "gamer";

export const SESSION_INITIALIZING = "SESSION_INITIALIZING";
export const SESSION_WAITING_FOR_PARTICIPANTS =
  "SESSION_WAITING_FOR_PARTICIPANTS";
export const SESSION_PENDING_LAUNCH = "SESSION_PENDING_LAUNCH";
export const SESSION_IN_PROGRESS = "SESSION_IN_PROGRESS";
export const SESSION_FORCE_FINISHED = "SESSION_FORCE_FINISHED";
export const SESSION_ABORTED = "SESSION_ABORTED";
export const SESSION_COMPLETED = "SESSION_COMPLETED";
export const SESSION_COMPLETED_NEED_MORE_INFO =
  "SESSION_COMPLETED_NEED_MORE_INFO";
export const SESSION_COMPLETED_WITH_UNDOABLE =
  "SESSION_COMPLETED_WITH_UNDOABLE";
export const SESSION_COMPLETED_WITH_MISSING_ESTIMATES =
  "SESSION_COMPLETED_WITH_MISSING_ESTIMATES";
export const SESSION_RUN_AGAIN = "SESSION_RUN_AGAIN";
export const SESSION_RUN_AGAIN_FRESH = "SESSION_RUN_AGAIN_FRESH";

export const ESTIMATE_TIME_LIMIT = 30;
export const ESTIMATE_NOT_GIVEN = "ESTIMATE_NOT_GIVEN";
export const ESTIMATE_NEEDS_MORE_INFO = "ESTIMATE_NEEDS_MORE_INFO";
export const ESTIMATE_IS_UNDOABLE = "ESTIMATE_IS_UNDOABLE";
