export const LOCAL_STORAGE_USER_ID = "planning_poker_id";
export const LOCAL_STORAGE_USER_NAME = "planning_poker_username";

export const SCALE_FIBONACCI = "fibonacci";
export const SCALE_T_SHIRT = "t_shirt";
export const SCALE_GAMER = "gamer";

export const SESSION_INITIALIZING = "SESSION_INITIALIZING";
export const SESSION_WAITING_FOR_PARTICIPANTS = "SESSION_WAITING_FOR_PARTICIPANTS";
export const SESSION_PENDING_LAUNCH = "SESSION_PENDING_LAUNCH";
export const SESSION_IN_PROGRESS = "SESSION_IN_PROGRESS";
export const SESSION_FINISHED = "SESSION_FINISHED";
export const SESSION_ABORTED = "SESSION_ABORTED";

export const ESTIMATE_TIME_LIMIT = 30;
export const ESTIMATE_TIMER_EXPIRED = "ESTIMATE_TIMER_EXPIRED";
export const ESTIMATE_NEEDS_MORE_INFO = "ESTIMATE_NEEDS_MORE_INFO";
export const ESTIMATE_IS_UNDOABLE = "ESTIMATE_IS_UNDOABLE";
