export const SEND_TO_SERVER = "SEND_TO_SERVER";
export const RECEIVE_FROM_SERVER = "RECEIVE_FROM_SERVER";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LIST_UPDATE = "USER_LIST_UPDATE";
export const CURRENT_USER_LOG_IN = "CURRENT_USER_LOG_IN";
export const CURRENT_USER_LOG_OUT = "CURRENT_USER_LOG_OUT";

export const ADD_SESSION = "ADD_SESSION";
export const REMOVE_SESSION = "REMOVE_SESSION";
